# Generated by Django 6.0.3 on 2026-04-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('ktp', 'KTP'), ('sim', 'SIM'), ('other', 'Lainnya')], max_length=20)),
                ('country', models.CharField(choices=[('ID', 'Indonesia'), ('SG', 'Singapura'), ('MY', 'Malaysia'), ('TH', 'Thailand'), ('PH', 'Filipina'), ('VN', 'Vietnam'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('KR', 'Korea'), ('JP', 'Jepang'), ('CN', 'China'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('US', 'Amerika Serikat'), ('UK', 'Inggris'), ('DE', 'Jerman'), ('FR', 'Prancis'), ('IT', 'Italia'), ('ES', 'Spanyol'), ('NL', 'Belanda'), ('CH', 'Swiss'), ('AT', 'Austria'), ('SE', 'Swedia'), ('NO', 'Norwegia'), ('DK', 'Denmark'), ('FI', 'Finlandia'), ('PL', 'Polandia'), ('CZ', 'Czech'), ('GR', 'Yunani'), ('PT', 'Portugis'), ('BE', 'Belgia'), ('BR', 'Brazil'), ('MX', 'Meksiko'), ('CA', 'Kanada'), ('IN', 'India'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('AE', 'UAE'), ('SA', 'Arab Saudi'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('EG', 'Mesir'), ('ZA', 'Afrika Selatan'), ('NG', 'Nigeria'), ('KE', 'Kenya')], max_length=2)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='auth_system.member')),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
                'unique_together': {('member', 'document_number')},
            },
        ),
    ]
