# Generated by Django 6.0.3 on 2026-04-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = []
