# Generated by Django 6.0.3 on 2026-04-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='country_code',
            field=models.CharField(default='+62', max_length=6),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(default='Indonesia', max_length=80),
        ),
        migrations.AddField(
            model_name='member',
            name='salutation',
            field=models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('dr', 'Dr')], default='mr', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='country_code',
            field=models.CharField(default='+62', max_length=6),
        ),
        migrations.AddField(
            model_name='staff',
            name='maskapai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='auth_system.maskapai'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(default='Indonesia', max_length=80),
        ),
        migrations.AddField(
            model_name='staff',
            name='salutation',
            field=models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('dr', 'Dr')], default='mr', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('customer_service', 'Customer Service'), ('operations', 'Operations'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('admin', 'Admin')], default='admin', max_length=30),
        ),
    ]
