# Generated by Django 6.0.3 on 2026-04-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimmissingmiles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='identity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transfermiles',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='country_code',
            field=models.CharField(default='+62', max_length=6),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(default='Indonesia', max_length=80),
        ),
        migrations.AddField(
            model_name='member',
            name='salutation',
            field=models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('dr', 'Dr')], default='mr', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='country_code',
            field=models.CharField(default='+62', max_length=6),
        ),
        migrations.AddField(
            model_name='staff',
            name='maskapai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='auth_system.maskapai'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(default='Indonesia', max_length=80),
        ),
        migrations.AddField(
            model_name='staff',
            name='salutation',
            field=models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('dr', 'Dr')], default='mr', max_length=10),
        ),
        migrations.AlterField(
            model_name='identity',
            name='country',
            field=models.CharField(max_length=80),
        ),
    ]
