# Generated by Django 6.0.3 on 2026-04-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_member_birth_date_member_country_code_and_more'),
        ('auth_system', '0003_alter_claimmissingmiles_options_and_more'),
    ]

    operations = [
    ]
