# Generated by Django 6.0.4 on 2026-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_merge_20260430_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimmissingmiles',
            options={'verbose_name': 'Claim Missing Miles', 'verbose_name_plural': 'Claim Missing Miles'},
        ),
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name': 'Identity', 'verbose_name_plural': 'Identities'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterModelOptions(
            name='transfermiles',
            options={'verbose_name': 'Transfer Miles', 'verbose_name_plural': 'Transfer Miles'},
        ),
        migrations.AlterField(
            model_name='identity',
            name='country',
            field=models.CharField(choices=[('ID', 'Indonesia'), ('SG', 'Singapura'), ('MY', 'Malaysia'), ('TH', 'Thailand'), ('PH', 'Filipina'), ('VN', 'Vietnam'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('KR', 'Korea'), ('JP', 'Jepang'), ('CN', 'China'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('US', 'Amerika Serikat'), ('UK', 'Inggris'), ('DE', 'Jerman'), ('FR', 'Prancis'), ('IT', 'Italia'), ('ES', 'Spanyol'), ('NL', 'Belanda'), ('CH', 'Swiss'), ('AT', 'Austria'), ('SE', 'Swedia'), ('NO', 'Norwegia'), ('DK', 'Denmark'), ('FI', 'Finlandia'), ('PL', 'Polandia'), ('CZ', 'Czech'), ('GR', 'Yunani'), ('PT', 'Portugis'), ('BE', 'Belgia'), ('BR', 'Brazil'), ('MX', 'Meksiko'), ('CA', 'Kanada'), ('IN', 'India'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('AE', 'UAE'), ('SA', 'Arab Saudi'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('EG', 'Mesir'), ('ZA', 'Afrika Selatan'), ('NG', 'Nigeria'), ('KE', 'Kenya')], max_length=2),
        ),
        migrations.AlterField(
            model_name='identity',
            name='document_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('customer_service', 'Customer Service'), ('operations', 'Operations'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('admin', 'Admin')], default='admin', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together={('member', 'document_number')},
        ),
    ]
