# Generated by Django 5.2.5 on 2026-05-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_merge_20260430_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('minimal_tier_miles', models.BigIntegerField(help_text='Minimum miles required for this tier')),
                ('minimal_frekuensi_terbang', models.IntegerField(help_text='Minimum flight frequency for this tier')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tier',
                'verbose_name_plural': 'Tiers',
                'ordering': ['minimal_tier_miles'],
            },
        ),
        migrations.AlterModelOptions(
            name='claimmissingmiles',
            options={'verbose_name': 'Claim Missing Miles', 'verbose_name_plural': 'Claim Missing Miles'},
        ),
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name': 'Identity', 'verbose_name_plural': 'Identities'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterModelOptions(
            name='transfermiles',
            options={'verbose_name': 'Transfer Miles', 'verbose_name_plural': 'Transfer Miles'},
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='award_miles',
            field=models.BigIntegerField(default=0, help_text='Miles available for redeeming rewards'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='country',
            field=models.CharField(choices=[('ID', 'Indonesia'), ('SG', 'Singapura'), ('MY', 'Malaysia'), ('TH', 'Thailand'), ('PH', 'Filipina'), ('VN', 'Vietnam'), ('TW', 'Taiwan'), ('HK', 'Hong Kong'), ('KR', 'Korea'), ('JP', 'Jepang'), ('CN', 'China'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('US', 'Amerika Serikat'), ('UK', 'Inggris'), ('DE', 'Jerman'), ('FR', 'Prancis'), ('IT', 'Italia'), ('ES', 'Spanyol'), ('NL', 'Belanda'), ('CH', 'Swiss'), ('AT', 'Austria'), ('SE', 'Swedia'), ('NO', 'Norwegia'), ('DK', 'Denmark'), ('FI', 'Finlandia'), ('PL', 'Polandia'), ('CZ', 'Czech'), ('GR', 'Yunani'), ('PT', 'Portugis'), ('BE', 'Belgia'), ('BR', 'Brazil'), ('MX', 'Meksiko'), ('CA', 'Kanada'), ('IN', 'India'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('AE', 'UAE'), ('SA', 'Arab Saudi'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('EG', 'Mesir'), ('ZA', 'Afrika Selatan'), ('NG', 'Nigeria'), ('KE', 'Kenya')], max_length=2),
        ),
        migrations.AlterField(
            model_name='identity',
            name='document_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together={('member', 'document_number')},
        ),
        migrations.AddField(
            model_name='member',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='auth_system.tier'),
        ),
    ]
