# Generated by Django 6.0.4 on 2026-04-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_alter_claimmissingmiles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadiah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_hadiah', models.CharField(max_length=20, unique=True)),
                ('nama_hadiah', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('miles_diperlukan', models.BigIntegerField()),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif'), ('discontinued', 'Dihentikan')], default='active', max_length=20)),
                ('tanggal_valid_mulai', models.DateField()),
                ('tanggal_valid_akhir', models.DateField()),
                ('jumlah_tersedia', models.IntegerField(default=0)),
                ('jumlah_terjual', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mitra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hadiah_list', to='auth_system.mitra')),
                ('penyedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiah_list', to='auth_system.penyedia')),
            ],
            options={
                'verbose_name': 'Hadiah',
                'verbose_name_plural': 'Hadiah',
                'ordering': ['-created_at'],
            },
        ),
    ]
