# Generated by Django 5.2.5 on 2026-05-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_tier_alter_claimmissingmiles_options_and_more'),
        ('auth_system', '0006_hadiah'),
    ]

    operations = [
    ]
