# Generated by Django 6.0.4 on 2026-05-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0007_merge_20260512_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardMilesPackage',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('harga_paket', models.DecimalField(decimal_places=2, max_digits=15)),
                ('jumlah_award_miles', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Award Miles Package',
                'verbose_name_plural': 'Award Miles Packages',
                'ordering': ['jumlah_award_miles'],
            },
        ),
        migrations.CreateModel(
            name='Bandara',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bandara',
                'verbose_name_plural': 'Bandara',
                'ordering': ['iata_code'],
            },
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='kelas_kabin',
            field=models.CharField(blank=True, choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='maskapai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='auth_system.maskapai'),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='pnr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claimmissingmiles',
            name='miles_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='bandara_asal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_asal', to='auth_system.bandara'),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='bandara_tujuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_tujuan', to='auth_system.bandara'),
        ),
        migrations.CreateModel(
            name='MemberAwardMilesPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('award_miles_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='auth_system.awardmilespackage')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to='auth_system.member')),
            ],
            options={
                'verbose_name': 'Member Award Miles Package',
                'verbose_name_plural': 'Member Award Miles Packages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('miles_used', models.BigIntegerField()),
                ('hadiah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redeems', to='auth_system.hadiah')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeems', to='auth_system.member')),
            ],
            options={
                'verbose_name': 'Redeem',
                'verbose_name_plural': 'Redeems',
                'ordering': ['-timestamp'],
            },
        ),
    ]
