# Generated by Django 6.0.4 on 2026-05-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_awardmilespackage_bandara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitra',
            name='tanggal_kerja_sama',
            field=models.DateField(blank=True, null=True),
        ),
    ]
